### PR TITLE
Replace custom python in ubuntu2010-gcc10

### PR DESCRIPTION
**Pull request by RafaelPalomar**
This replaces the custom python installation by installation using the
package manager. This helps creating an environment closer to that the
users can find in a fresh Ubuntu install.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks again for working on this :pray: 

Closing. It turns out this PR has been superseded by https://github.com/dockbuild/dockbuild/pull/78 removing the Ubuntu 20.10 image that reached end of life (EOL) in July, 2020.

See https://endoflife.software/operating-systems/linux/ubuntu
and https://ubuntu.com/about/release-cycle

**Comment by RafaelPalomar** [comment]
@jcfr, EOL for Ubuntu 20.10 will be in July 2022. But maybe at this point is more interesting to include newer releases instead of using energy on 20.10 this close to EOL.

**Comment by jcfr** [comment]
> EOL for Ubuntu 20.10 will be in July 2022

Good catch.

Once https://github.com/dockbuild/dockbuild/pull/79 is finalized, I look into re-enabling Ubuntu 20.10.

For the sake of using dockbuild to easily build software packages, having a consistent python version is likely preferable.

Now for having a system that matches what the developer would be using, having the system python is preferable and under that assumption, you proposed patch makes complete sense. That said, the same argument should likely apply for cmake, git, etc ...

To address the part "what the user have by default", I am wondering if creating (or using an existing) a GitHub action allowing to do somewhat the "equivalent" of https://www.browserstack.com for linux, macOS and Windows using either docker images or VM provided by the CI services ...

**Comment by jamesobutler** [comment]
Ubuntu 20.10 went EOL July 2021.
Ubuntu 21.10 goes EOL July 2022.

20.10 shouldn’t need to be re-enabled as it has indeed gone EOL.

**Comment by jamesobutler** [comment]
As it relates to the Ubuntu 21.04 environment here in this rep, that has also gone EOL as of a couple days ago.

**Comment by RafaelPalomar** [comment]
> Ubuntu 20.10 went EOL July 2021. Ubuntu 21.10 goes EOL July 2022.
> 
> 20.10 shouldn’t need to be re-enabled as it has indeed gone EOL.

Thank you, @jamesobutler, you are right. @jcfr, sorry for the confusion.

**Pull request closed without merging**
