### PR TITLE
Update CMake and ninja

### PR DESCRIPTION
**Pull request by phcerdan**
CMake from v3.12.1 to v3.13.4
Ninja from v1.8.2.g3bbbe to v1.9.0.g5b44b

### CODE REVIEW

**Comment by jcfr** [comment]
Cam you accept the invite to the repo ? This should allow the CI to be triggered by force pushing the commit. (`git commit --amend --no-edit`)

image

**Comment by phcerdan** [comment]
Accepted, thanks!
I `push -f` after amend, but CI wasn't triggered

**Comment by jcfr** [comment]
I just enabled the build of PR from forks. Could you try again ?

**Comment by jcfr** [comment]
image

**Comment by phcerdan** [comment]
Nice, now is working!

**Comment by jcfr** [comment]
Please, publish a new release of the CMake binaries for centos5/manylinux. See details at https://github.com/dockbuild/CMake/

I just added you as a collaborator to the project so that you can upload the release package

**Comment by phcerdan** [comment]
Cool, I was finding out about that just now. On my way.

**Comment by jcfr** [comment]
The link  doesn't work ftp://ftp.openssl.org/source/openssl-1.0.2o.tar.gz

This one is now the correct one:  ftp://ftp.openssl.org/source/openssl-1.0.2r.tar.gz

Since the script in dockcross have been udpated, considering running https://github.com/dockbuild/dockbuild/blob/master/imagefiles/UpdateFromUpstream.sh

**Comment by phcerdan** [comment]
I just opened #57 with the result of UpdateFromUpstream.sh (dockcross update)

**Comment by jcfr** [comment]
As soon as dockbuild CI has completed, the CI workflow could be restarted.

image

**Comment by phcerdan** [comment]
Rebased on top of master

**Pull request merged**
